Add basic functionalities for StarkBank and StarkInfra SDKs
starkinfra/core-php pull request #1
Opened 2022-09-14 23:10 UTC by delsonb-stark

2022-09-15 20:16 UTC, xavier-stark requested changes

2022-09-15 20:16 UTC, xavier-stark commented on src/error.php
> +
Remover espaço

2022-09-15 20:16 UTC, xavier-stark commented on src/key.php
> +
Remover Linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/api.php
> +
Excluir linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/case.php
> +class StringCase
2 linhas após import/namespace

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/checks.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/datetime.php
> +class StarkDateTime {
2 linhas após classes 1 após funções

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/enum.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/parse.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/request.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/resource.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/rest.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on src/utils/request.php
> +            if (count($parts) > 1) //HTTP/1.0 <code> <text>
Remover comentario

2022-09-15 20:16 UTC, xavier-stark commented on tests/testRestGet.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on tests/testRestGet.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on tests/testRestGet.php
> +
Remover linha

2022-09-15 20:16 UTC, xavier-stark commented on tests/utils/user.php
> +
Remover linha

2022-09-19 17:18 UTC, xavier-stark requested changes

2022-09-19 17:18 UTC, xavier-stark commented on src/user/__publicuser.php
> +class PublicUSer
PublicUSer -> PublicUser

2022-09-19 18:04 UTC, xavier-stark requested changes

2022-09-19 18:04 UTC, xavier-stark commented on src/utils/request.php
> +        if ($user instanceof PublicUSer)
PublicUSer -> PublicUser
Da um replace all que fica tudo certo :D

2022-09-19 18:04 UTC, xavier-stark commented on src/utils/request.php
> +use StarkCore\PublicUSer;
Here too :D

2022-09-19 19:49 UTC, xavier-stark approved these changes

2022-09-28 13:59 UTC, cdottori-stark commented on composer.json
> +        "openbanking"
acho que seria bom colocar a tag stark aqui também

2022-09-28 14:03 UTC, cdottori-stark approved these changes

2022-09-28 14:08 UTC, delsonb-stark commented on composer.json
> +        "openbanking"
Done

2022-09-28 14:13 UTC, merged